collections:
  authors: 
    output: true

destination: docs/

sass:
    load_paths:
        - _sass
        - node_modules

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

include: ["node_modules"]
exclude: []